runmode: debug               # 开发模式, debug, release, test
addr: :30000                 # HTTP绑定端口
name: demo02_app             # API Server的名字
url: http://localhost:8080   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数
